version: '3'

services:
  app:
    image: fiverrclone
    build:
      context: .
      dockerfile: Dockerfile
      container_name: fiverrclone
    ports:
      - 3000: 3000
      - 8000: 8000
